import type { Decorator, Preview } from '@storybook/react-vite';
import '../src/styles.css';
import './preview.css';

// Размер экрана: макеты Figma — 393×852; остальное — проверка резиновой вёрстки
const devices: Record<string, { title: string; width: number; height: number }> = {
  s320: { title: '320 × 568 · маленький (SE 1)', width: 320, height: 568 },
  a360: { title: '360 × 800 · Android', width: 360, height: 800 },
  s375: { title: '375 × 667 · iPhone SE 3', width: 375, height: 667 },
  i393: { title: '393 × 852 · iPhone 15 (Figma)', width: 393, height: 852 },
  m430: { title: '430 × 932 · iPhone 15 Pro Max', width: 430, height: 932 },
};

const withTheme: Decorator = (Story, context) => {
  const theme = (context.globals.theme as string) ?? 'light';
  const device = devices[(context.globals.device as string) ?? 'i393'] ?? devices.i393;
  if (typeof document !== 'undefined') {
    document.documentElement.dataset.theme = theme;
  }
  return (
    <div className="sb-canvas" data-theme={theme} style={{ ['--screen-width' as string]: `${device.width}px`, ['--screen-height' as string]: `${device.height}px` }}>
      <Story />
    </div>
  );
};

const preview: Preview = {
  decorators: [withTheme],
  globalTypes: {
    theme: {
      description: 'Тема',
      toolbar: {
        title: 'Тема',
        icon: 'mirror',
        items: [
          { value: 'light', title: 'Светлая', icon: 'sun' },
          { value: 'dark', title: 'Тёмная', icon: 'moon' },
        ],
        dynamicTitle: true,
      },
    },
    device: {
      description: 'Размер экрана',
      toolbar: {
        title: 'Экран',
        icon: 'mobile',
        items: Object.entries(devices).map(([value, d]) => ({ value, title: d.title })),
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: { theme: 'light', device: 'i393' },
  parameters: {
    layout: 'centered',
    controls: { expanded: true, sort: 'requiredFirst' },
    backgrounds: { disable: true },
    a11y: { test: 'todo' }, // addon-a11y: нарушения видны в панели, но не валят тесты
    options: {
      storySort: {
        order: [
          'Старт',
          [
            'Быстрый старт', 'О проекте', 'Введение', 'Принципы', 'Атомарная система', 'Как пользоваться',
            'Прототип', 'Процессы', ['Figma ↔ код', 'iOS и Android', 'Ресурсы'], 'Для разработчиков', ['Обзор', 'Примитивы'],
          ],
          'Foundations',
          ['Токены и семантика', 'Типографика', 'Отступы и радиусы', 'Иконки', 'Скролл и края экрана', 'Резиновая вёрстка', 'Анимации', 'Тексты и тон'],
          'Atoms',
          'Molecules',
          'Organisms',
          'Templates',
          ['Screen', 'DetailsScreen', 'Prose'],
          'Pages',
          [
            'Экраны флоу',
            // flow-order:start — копия src/docs/flow-order.ts, править там и запускать node scripts/flow-order.mjs
            [
              'App / Splash',
              'Onboarding / Welcome',
              'Auth / Sign In',
              'Auth / Password Recovery',
              'Auth / Password Recovery / Dialog / Sent',
              'Onboarding / Name / Focused',
              'Onboarding / First Item Prompt',
              'Onboarding / First Item / Sheet / Add Photo',
              'Onboarding / First Outfit / Preview',
              'Outfits / Everyday / Sunny',
              'Outfits / Everyday / Rain Alert',
              'Outfits / Everyday / Occasion Selector Open',
              'Outfits / Everyday / Sheet / Custom Occasion Name Empty',
              'Outfits / Everyday / Sheet / Custom Occasion Name Entered',
              'Outfits / Everyday / Wear Action Active',
              'Outfits / Recommendations / Empty Wardrobe',
              'Wardrobe / Items / Empty',
              'Wardrobe / Items / Populated',
              'Wardrobe / Items / Populated / Scrolled',
              'Wardrobe / Items / Sheet / Category Root',
              'Wardrobe / Items / Sheet / Category',
              'Wardrobe / Items / Sheet / Season Filter',
              'Wardrobe / Items / Sheet / Tags Filter',
              'Wardrobe / Items / No Filter Results',
              'Wardrobe / Items / Sheet / Item Actions',
              'Wardrobe / Item / Toast',
              'Wardrobe / Item Search / Query Focused',
              'Wardrobe / Item Search / Results',
              'Wardrobe / Item Search / No Results',
              'Wardrobe / Item Details',
              'Wardrobe / Item Details / Scrolled',
              'Wardrobe / Edit Item / Sheet / Category Expanded',
              'Wardrobe / Edit Item / Sheet / Color',
              'Wardrobe / Edit Item / Sheet / Season',
              'Wardrobe / Outfits / Empty',
              'Wardrobe / Outfits / Populated',
              'Wardrobe / Outfits / Sheet / Occasion Filter',
              'Wardrobe / Outfits / Sheet / Custom Occasion Name Empty',
              'Wardrobe / Outfits / Sheet / Custom Occasion Name Entered',
              'Wardrobe / Outfits / No Filter Results',
              'Wardrobe / Outfit / Sheet / Actions',
              'Wardrobe / Outfit / Sheet / Permanent Delete Actions',
              'Wardrobe / Outfit Details',
              'Wardrobe / Outfit Details / Scrolled',
              'Wardrobe / Outfit Details / Variant 02',
              'Wishlist / Items / Empty',
              'Wishlist / Items / Populated',
              'Wishlist / Items / Scrolled',
              'Wishlist / Add / Sheet / Content Type',
              'Wishlist / New Item / Empty',
              'Wishlist / New Item / Completed',
              'Wishlist / Item / Sheet / Actions',
              'Wishlist / Item / Toast / Moved to Wardrobe',
              'Wishlist / Item Details',
              'Wishlist / Item Details / Scrolled',
              'Wishlist / Outfits / Populated',
              'Wishlist / Outfit Details / Default',
              'Archive / Items / Empty',
              'Archive / Items / Populated',
              'Archive / Item / Sheet / Actions',
              'Archive / Item / Toast / Moved to Trash',
              'Trash / Items / Empty',
              'Trash / Items / Populated',
              'Trash / Item / Sheet / Actions',
              'Trash / Item / Toast / Deleted Permanently',
              'Trash / Items / Dialog / Clear',
              'New Item / Details / No Photo Variant 01',
              'New Item / Details / No Photo Variant 02',
              'New Item / Photo / Sheet / Add',
              'New Item / Photo / Removing Background Variant 01',
              'New Item / Removing Background',
              'New Item / Details / Photo Added Variant 01',
              'New Item / Details / Photo Added Variant 02',
              'New Item / Details / Name Focused Variant 01',
              'New Item / Details / Name Focused Variant 02',
              'New Item / Details / Sheet / Category Root',
              'New Item / Details / Sheet / Category Expanded',
              'New Item / Details / Completed Variant 01',
              'New Item / Details / Completed Variant 02',
              'Outfit Creation / Item Selection / Items Selected',
              'Outfit Creation / Item Selection / Ready to Continue',
              'Outfit Creation / Items / Sheet / Category with Selection',
              'Outfit Creation / Shuffle / Dialog / Unsaved Changes',
              'Outfit Creation / Canvas / Gesture Hint',
              'Outfit Creation / Canvas / Default',
              'Outfit Creation / Item Filter / Sheet / Bottoms',
              'Outfit Creation / Canvas / Filtered',
              'Outfit Creation / Clear / Dialog / Confirmation',
              'Outfit Creation / Exit / Dialog / Unsaved Changes',
              'Outfit Creation / Criteria / Default',
              'Search / Discover',
              'Search / Text / Query Focused',
              'Search / Text / Results',
              'Search / Results / Sheet / Sorting',
              'Search / Results / Sheet / Price Filter',
              'Search / Text / No Results Filtered',
              'Search / Result Item / Toast / Moved to Wishlist',
              'Search / Photo / Sheet / Add',
              'Search / Photo / Crop',
              'Search / Photo / Query Focused',
              'Search / Photo / Results',
              'Search / Photo / Sheet / Replace',
              'Stylist / Catalog',
              'Stylist / Assistant / Input Focused',
              'Stylist / Home / Greeting Entered',
              'Stylist / Home / Message Ready',
              'Stylist / Outfit of the Day / Default',
              'Stylist / Outfit of the Day / Dialog / About Surprise Me',
              'Stylist / Outfit of the Day / No More Outfits',
              'Stylist / Constructor / Empty',
              'Stylist / What to Wear / Outfits',
              'Stylist / Trips / List',
              'Stylist / Trip Details / Outfits Tab',
              'Stylist / Trip Details / Items Tab',
              'Profile / Overview / Single Account',
              'Profile / Overview / Analytics',
              'Profile / Overview / Analytics / Scrolled',
              'Profile / Analytics / Sheet / Period',
              'Profile / Accounts / Sheet / Single',
              'Profile / Accounts / Sheet / List',
              'Profile / Edit / No Avatar',
              'Profile / Avatar / Sheet / Add',
              'Profile / Edit / Avatar Added',
              'Profile / Avatar / Sheet / Replace',
              'Profile / Edit / Sheet / Birth Year',
              'Profile / Edit / Sheet / Gender',
              'Profile / Edit / Sheet / Style',
              'Settings / Main',
              'Settings / Country / Sheet / Default',
              'Settings / Country / Sheet / Search Focused',
              'Settings / Currency / Sheet / Default',
              'Settings / Sign Out / Dialog / Confirmation',
              'Settings / Delete Account / Dialog / Confirmation',
              'Legal / Privacy Policy / May 2026',
              'Legal / Terms of Use / May 2026',
            ],
            // flow-order:end
          ],
        ],
        // имена историй участвуют в сортировке: порядок экранов Pages по пути пользователя (#174)
        includeNames: true,
      },
    },
  },
};

export default preview;
